# Generated by Django 6.0.6 on 2026-06-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_delete_tag_alter_quote_tags'),
        ('tags', '0002_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='tags',
            field=models.ManyToManyField(related_name='quotes', to='tags.tag'),
        ),
    ]
