"""
Django settings for authors project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from .config import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path( __file__ ).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r*9ttx8rh3k-f(=s+#&q23xz=5_u2)yyvnp8r#36fiw*ew!i$g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [ ]

# Application definition

INSTALLED_APPS = [ 'django.contrib.admin',
		'django.contrib.auth',
		'django.contrib.contenttypes',
		'django.contrib.sessions',
		'django.contrib.messages',
		'django.contrib.staticfiles',
		'quotes',
		'authors',
		'tags',
		'users',
		'external_sources',
		]

MIDDLEWARE = [ 'django.middleware.security.SecurityMiddleware',
		'django.contrib.sessions.middleware.SessionMiddleware',
		'django.middleware.common.CommonMiddleware',
		'django.middleware.csrf.CsrfViewMiddleware',
		'django.contrib.auth.middleware.AuthenticationMiddleware',
		'django.contrib.messages.middleware.MessageMiddleware',
		'django.middleware.clickjacking.XFrameOptionsMiddleware',
		]

ROOT_URLCONF = 'quotes_and_authors.urls'

TEMPLATES = [ {
		'BACKEND':  'django.template.backends.django.DjangoTemplates',
		'DIRS':     [ BASE_DIR / 'quotes_and_authors' / 'templates' ],
		'APP_DIRS': True,
		'OPTIONS':  {
				'context_processors': [ 'django.template.context_processors.request',
						'django.contrib.auth.context_processors.auth',
						'django.contrib.messages.context_processors.messages',
						],
				},
		},
		]

WSGI_APPLICATION = 'quotes_and_authors.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
		"default": {
				"ENGINE":   "django.db.backends.postgresql",
				"NAME":     config.POSTGRES_DB,
				"USER":     config.POSTGRES_USER,
				"PASSWORD": config.POSTGRES_PASSWORD,
				"HOST":     config.POSTGRES_HOST_IP,
				"PORT":     config.POSTGRES_PORT,
				},
		}

# Email

EMAIL_BACKEND = config.MAIL_BACKEND

EMAIL_HOST = config.EMAIL_HOST
EMAIL_PORT = config.MAIL_PORT_SMTP

EMAIL_HOST_USER = config.MAIL_HOST_USER
EMAIL_HOST_PASSWORD = config.MAIL_HOST_PASSWORD

EMAIL_USE_SSL = config.MAIL_USE_SSL
EMAIL_USE_TLS = config.MAIL_USE_TLS

DEFAULT_FROM_EMAIL = config.MAIL_FROM

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [ { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
		}, { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
		}, { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
		}, { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
		},
		]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

APPEND_SLASH = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATICFILES_DIRS = [ BASE_DIR / 'quotes_and_authors' / 'static' ]
STATIC_URL = 'static/'

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'

LOGOUT_REDIRECT_URL = '/'
